.TH HAMFAX 1 

.SH NAME
hamfax \- Qt based shortwave fax

.SH SYNOPSIS
.B hamfax

.SH DESCRIPTION
.B hamfax
is a program for sending and receiving fax images. 
This is a mode used by hamradio operators. 
Hamfax uses a soundcard to send and receive images.

.SH SEE ALSO
The hamfax documentation in html format in
/usr/share/HamFax/HamFax.html, which can be viewed
from within hamfax.
